// Store selected element info
let currentElementInfo = null;

// DOM elements
const selectElementBtn = document.getElementById('selectElement');
const captureButton = document.getElementById('captureButton');
const clearButton = document.getElementById('clearButton');
const memoTextarea = document.getElementById('memo');
const elementInfoContainer = document.getElementById('elementInfoContainer');
const elementInfoDiv = document.getElementById('elementInfo');
const statusMessage = document.getElementById('statusMessage');

// Event listeners
selectElementBtn.addEventListener('click', startElementSelection);
captureButton.addEventListener('click', captureToMarkdown);
clearButton.addEventListener('click', clearAll);

// Listen for messages from content script
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (request.action === 'elementSelected') {
        currentElementInfo = request.elementInfo;
        displayElementInfo(request.elementInfo);
        captureButton.disabled = false;
        showStatus('DOM 요소가 선택되었습니다!', 'success');
    }
});

async function startElementSelection() {
    try {
        // Get current active tab
        const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });

        console.log('Current tab URL:', tab.url);

        // Check if we can access the tab (not chrome:// or extension pages)
        if (!tab.url || tab.url.startsWith('chrome://') || tab.url.startsWith('chrome-extension://') || tab.url.startsWith('edge://')) {
            showStatus(`이 페이지에서는 사용할 수 없습니다. (현재: ${tab.url || 'undefined'})`, 'error');
            return;
        }

        // Try to inject content script dynamically if not already loaded
        try {
            await chrome.scripting.executeScript({
                target: { tabId: tab.id },
                files: ['content.js']
            });

            await chrome.scripting.insertCSS({
                target: { tabId: tab.id },
                files: ['content.css']
            });
        } catch (e) {
            // Script might already be injected, continue
            console.log('Script injection attempt:', e);
        }

        // Small delay to ensure script is loaded
        await new Promise(resolve => setTimeout(resolve, 100));

        // Send message to content script to start selection
        chrome.tabs.sendMessage(tab.id, { action: 'startSelection' }, (response) => {
            if (chrome.runtime.lastError) {
                showStatus('오류: 페이지를 새로고침하거나 다시 시도해주세요.', 'error');
                console.error('Message error:', chrome.runtime.lastError);
                return;
            }
            if (response && response.success) {
                showStatus('페이지에서 DOM 요소를 클릭하세요...', 'info');
            }
        });
    } catch (error) {
        showStatus('오류: ' + error.message, 'error');
        console.error('Selection error:', error);
    }
}

function displayElementInfo(info) {
    elementInfoContainer.style.display = 'block';
    elementInfoDiv.innerHTML = `
        <div><strong>Tag:</strong> ${info.tag}</div>
        ${info.id ? `<div><strong>ID:</strong> ${info.id}</div>` : ''}
        ${info.classes ? `<div><strong>Classes:</strong> ${info.classes}</div>` : ''}
        <div><strong>Selector:</strong></div>
        <pre>${info.selector}</pre>
        ${info.text ? `<div><strong>Text:</strong> ${info.text}${info.text.length >= 100 ? '...' : ''}</div>` : ''}
    `;
}

function captureToMarkdown() {
    if (!currentElementInfo) {
        showStatus('먼저 DOM 요소를 선택해주세요.', 'error');
        return;
    }

    const memo = memoTextarea.value.trim();

    // Generate markdown content
    const timestamp = new Date().toISOString();
    const filename = `dom-capture-${Date.now()}.md`;

    const markdownContent = generateMarkdown(currentElementInfo, memo, timestamp);

    // Download the file
    downloadMarkdownFile(filename, markdownContent);

    showStatus('마크다운 파일이 다운로드되었습니다!', 'success');
}

function generateMarkdown(elementInfo, memo, timestamp) {
    return `# DOM Element Capture

## Capture Information
- **Date:** ${new Date(timestamp).toLocaleString('ko-KR')}
- **URL:** ${getCurrentTabUrl()}

## Element Details

### Tag Information
- **Tag:** \`${elementInfo.tag}\`
${elementInfo.id ? `- **ID:** \`${elementInfo.id}\`` : ''}
${elementInfo.classes ? `- **Classes:** \`${elementInfo.classes}\`` : ''}

### CSS Selector
\`\`\`css
${elementInfo.selector}
\`\`\`

### XPath
\`\`\`xpath
${elementInfo.xpath}
\`\`\`

${elementInfo.text ? `### Text Content
\`\`\`
${elementInfo.text}
\`\`\`
` : ''}

### HTML Structure
\`\`\`html
${elementInfo.html}${elementInfo.html.length >= 500 ? '...' : ''}
\`\`\`

## Memo
${memo || '_메모 없음_'}

---
*Generated by DOM Memo Capture Extension*
`;
}

function getCurrentTabUrl() {
    // This will be filled by the actual tab URL
    return window.currentTabUrl || 'Unknown';
}

// Store current tab URL when popup opens
chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
    if (tabs[0]) {
        window.currentTabUrl = tabs[0].url;
    }
});

function downloadMarkdownFile(filename, content) {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);

    chrome.downloads.download({
        url: url,
        filename: filename,
        saveAs: true
    }, (downloadId) => {
        if (chrome.runtime.lastError) {
            showStatus('다운로드 오류: ' + chrome.runtime.lastError.message, 'error');
        } else {
            // Clean up the object URL after a delay
            setTimeout(() => URL.revokeObjectURL(url), 1000);
        }
    });
}

function clearAll() {
    currentElementInfo = null;
    memoTextarea.value = '';
    elementInfoContainer.style.display = 'none';
    captureButton.disabled = true;
    statusMessage.innerHTML = '';
}

function showStatus(message, type = 'info') {
    statusMessage.innerHTML = `<div class="status ${type}">${message}</div>`;

    // Auto-hide after 5 seconds
    setTimeout(() => {
        if (statusMessage.innerHTML.includes(message)) {
            statusMessage.innerHTML = '';
        }
    }, 5000);
}
